---
# Only runs if nfs_volume_id is set

- name: Install python3-openstacksdk
  become: yes
  pip:
          name: openstacksdk
          executable: /usr/bin/pip3
  
- name: Make nfs shared data directory
  file:
          state: directory
          path: /home/ubuntu/data
          owner: ubuntu
          group: ubuntu

- name: Attach an OpenStack volume to the master instance
  os_server_volume:
          state: present
          server: "{{ ansible_hostname }}"
          volume: "{{ nfs_volume_id }}"
          device: /dev/vdb1
          auth:
                  auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
                  username: "{{ lookup('env', 'OS_USERNAME') }}"
                  password: "{{ lookup('env', 'OS_PASSWORD') }}"
                  project_name: "{{ lookup ('env', 'OS_PROJECT_NAME') }}"
                  os_user_domain_name: "{{ lookup ('env', 'OS_USER_DOMAIN_NAME') }}"
                  os_project_domain_name: "{{ lookup ('env', 'OS_PROJECT_DOMAIN_ID') }}"

- name: Restart nfs-kernel-server
  service: name=nfs-kernel-server state=started enabled=yes
